- README.md
- app/embeddings/milvus_embedding_store.py
- docker-compose.yml
- requirements.txt
- Added initial document loading into milvus.
- Updated docker compose to using milvus config
- Updated milvus config to use docker host name
> Gml 1586 load up starting documents in milvus

- app/embeddings/milvus_embedding_store.py
- app/main.py
- app/sync/eventual_consistency_checker.py
- tests/test_eventual_consistency_checker.py
- Added Eventual Consistency Checker and initialized it on SupportAI REST API calls
- Used the credentials from the db configs file for the TG connection
> GML-1545 - Sync - Upsert Vector Embeddings

- .github/workflows/build-deploy-ci.yaml
When the code is merged into the main branch, build a docker image with the first six digits of commitID tag like `tginternal/copilot:{$commit_sha::6}
`
Enter the k8s cluster and execute this command to replace the image value: 
`kubectl patch tigergraph/tg-47f94070-fa64-4191-b952-983dafabd8fb  -n 22a77be0-fb48-479d-b517-b6868326edd6 --type='json' -p='[{"op": "replace", "path": "/spec/sidecarContainers/1/image", "value": "tginternal/copilot:{$commit_sha::6}"}]'`
> TCE-3753 feat(cicd): Setup the github actions

- app/embeddings/milvus_embedding_store.py
- app/main.py
- udfs/milvus/rest/ExprUtil.hpp
Hardening milvus configs including update check for http prefix and port suffix in both embedding store and UDF
> UDF fix and embedding store init fix

- udfs/milvus/rest/ExprFunctions.hpp
- udfs/milvus/rest/ExprUtil.hpp
- Removed unnecessary static functions
- Changed port and top_k to int
- Using proper top_k parameter name (limit)
- More robust check on the URI input
> UDF Polish

- app/agent.py
- app/embeddings/embedding_services.py
- app/embeddings/milvus_embedding_store.py
- app/main.py
- app/metrics/prometheus_metrics.py
- app/metrics/tg_proxy.py
- app/supportai/retrievers/EntityRelationshipRetriever.py
- app/supportai/retrievers/HNSWOverlapRetriever.py
- app/supportai/retrievers/HNSWRetriever.py
- app/supportai/retrievers/HNSWSiblingRetriever.py
- app/supportai/supportai_ingest.py
- app/sync/eventual_consistency_checker.py
- app/tools/generate_function.py
- app/tools/map_question_to_schema.py
- udfs/milvus/rest/ExprUtil.hpp
- Added LLM metrics, TigerGraph db metrics and Milvus metrics
- Added the metrics endpoint
- Fixed the sync-ness of the eventual consistency checker
> GML-1542 - expose metrics endpoint

- .gitignore
- README.md
- app/embeddings/milvus_embedding_store.py
- app/main.py
- app/metrics/prometheus_metrics.py
- tests/test_milvus_embedding_store.py
- Added the copilot endpoint metrics as well
- In addition added the ability to disable the eventual consistency checker (and noted this in the readme)
> GML-1603 - Added metrics for the copilot endpoints as well

- app/embeddings/milvus_embedding_store.py
- app/main.py
- app/sync/eventual_consistency_checker.py
Make the consistency checker work on more loads after finishing
> GML-1604 - Consistency checker improvement

- .gitignore
- README.md
- app/agent.py
- app/embeddings/embedding_services.py
- app/embeddings/faiss_embedding_store.py
- app/embeddings/milvus_embedding_store.py
- app/llm_services/aws_bedrock_service.py
- app/llm_services/aws_sagemaker_endpoint.py
- app/llm_services/azure_openai_service.py
- app/llm_services/google_vertexai_service.py
- app/llm_services/openai_service.py
- app/main.py
- app/supportai/retrievers/BaseRetriever.py
- app/supportai/retrievers/EntityRelationshipRetriever.py
- app/sync/eventual_consistency_checker.py
- app/tools/generate_function.py
- app/tools/logging_utils.py
- app/tools/logwriter.py
- app/tools/map_question_to_schema.py
- app/tools/validation_utils.py
- log.INFO
- tests/test_eventual_consistency_checker.py
- tests/test_log_writer.py
- Added a unified LogWriter that has operational logging and audit logging
- Added operational logging and adhering to the recommended log structure
- "Format should be I0205 13:02:16.858685 698722 metafiles.cpp:2141] System_DSC|metadata copy validation"
- Altered http middleware to use LogWriter to output audit logs, which also adhere to the TigerGraph audit logs.
> GML-1541 - Operational Logging - Implement Structured Logging

- app/config.py
- app/embeddings/milvus_embedding_store.py
- app/main.py
- app/metrics/tg_proxy.py
- app/py_schemas/schemas.py
- app/routers/__init__.py
- app/routers/inquiryai.py
- app/routers/root.py
- app/routers/supportai.py
- app/tools/generate_function.py
- app/util.py
The only changes are in the inquiry router. Other changes are only formatting.
Don't merge after approval. I'll reformat the whole repo as the final commit.
> Rm json response

- app/routers/supportai.py
Added security for consistency status
> GML-1646 - Added security for openapi docs

- .github/workflows/onprem-build-nightly.yaml
Update the dev environment to use the latest dev images 
Jira ticket: https://graphsql.atlassian.net/browse/GML-1738
Tested in this github action run https://github.com/tigergraph/CoPilot/actions/runs/9424504968/job/25964840232.
> build(onprem-build-nightly): update dev environment on merge

- .github/workflows/onprem-build.yaml
Code changes:
* Update main workflow to pull docker images on the staging env and restart services, when code is merged to the main branch.
* Add a github secret for address of the staging env
Jira ticket: https://graphsql.atlassian.net/browse/GML-1739
> build(onprem-build): Add steps to update on-prem staging env

- .github/workflows/onprem-build-nightly.yaml
Summary:
* Update github action to build and push images for chat-history and ui when dev branch is pushed.
Test: https://github.com/tigergraph/CoPilot/actions/runs/9523259570/job/26254358020
> GML-1770: Add steps to build and push chat-history and ui

- copilot/app/agent/agent_graph.py
- copilot/app/agent/agent_rewrite.py
There are some small issues with the agent graph that causes error when querying the document graph from the chatbot.
> GML-1787: fix supportai for chatbot

- copilot-ui/src/actions/ActionProvider.tsx
- copilot-ui/src/components/Bot.tsx
- copilot-ui/src/components/Contexts.tsx
- copilot/app/routers/ui.py
- nginx/nginx.conf
Code change:
* Various places to make the graph selection working. Not the ideal fix but a clean fix would probably require a restructure of the react app. 
* As a byproduct, refreshing the chat page won't cause 404 error.
Test:
http://3.149.244.96/
> GML-1784: fix dropdown menu for graph selection

- copilot-ui/src/components/Bot.tsx
- copilot-ui/src/components/SideMenu.tsx
- copilot/app/routers/ui.py
* Remove the workspace selector
* Remove the menu section
> Minor UI fixes

- docker-compose.yml
"dependency cycle detected: chat-history -> copilot -> chat-history"
> GML-1796 dependency cycle detecte

- README.md
- common/gsql/supportai/Scan_For_Updates.gsql
- eventual-consistency-service/app/eventual_consistency_checker.py
- eventual-consistency-service/app/main.py
Updated ECC to let workers work take a processing node after the expire window.  Added more logging and options during configuration
> GML-1797 - Fix ECC - processing nodes

- copilot-ui/package.json
- copilot-ui/src/components/CustomChatMessage.tsx
- copilot-ui/src/components/Login.tsx
- copilot/app/agent/agent_graph.py
- nginx/nginx.conf
Code change:
* Render response as markdown
* Some minor fixes
Test:
http://3.15.238.52/
> Render markdown

- common/config.py
- copilot/app/routers/inquiryai.py
- copilot/app/routers/root.py
- copilot/app/routers/supportai.py
- copilot/app/routers/ui.py
Fix issue #235 by porting the fix for global health status. Currently there is only one service, the embedding store, being tracked. Consider adding other services such as chat history, ecc, etc., in the future.
> Issue #235: healthcheck uses hardcoded milvus config

- copilot-ui/src/actions/ActionProvider.tsx
Fixing build failure from [PR 252](https://github.com/tigergraph/CoPilot/pull/252)
> remove unused param causing build failure

- .github/workflows/pull-test-merge.yaml
- chat-history/config/config.go
- chat-history/config/config_test.go
- chat-history/main.go
- chat-history/routes/routes.go
- chat-history/routes/routes_test.go
- copilot/app/routers/supportai.py
- eventual-consistency-service/app/main.py
ECC couldn't connect to Milvus cloud without giving the alias parameter. Fixed in this small PR.
> Fix alias in ecc

- copilot-ui/public/user.svg
- copilot-ui/src/actions/ActionProvider.tsx
- copilot-ui/src/components/Interact.tsx
- copilot-ui/src/components/SideMenu.tsx
- copilot-ui/src/components/Start.tsx
- copilot-ui/src/components/UserAvatar.tsx
Code change:
* Hide mock configure menu
* Hide mock user profile
* Replace mock user picture with generic user icon
* Hide websocket status message
* Hide sample questions if the selected graph is not Transaction_Fraud or pyTigerGraph
Result:
> GML-1839: clean chat UI
